steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/claude-vertex-bridge', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/claude-vertex-bridge']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'claude-vertex-bridge'
      - '--image'
      - 'gcr.io/$PROJECT_ID/claude-vertex-bridge'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--service-account'
      - 'claude-vertex-bridge@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=${_REGION},GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json,VERTEX_AI_ENDPOINT=${_VERTEX_AI_ENDPOINT},API_KEYS=0CclcsPZlawIsH3cu24FNNvqo205iA171Gw5DkuD0oo'

substitutions:
  _REGION: us-east5  # Default region
  _VERTEX_AI_ENDPOINT: https://us-east5-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/us-east5/publishers/anthropic/models/claude-3-5-sonnet-v2@20241022:streamRawPredict

images:
  - 'gcr.io/$PROJECT_ID/claude-vertex-bridge'
